name: fingerprint_test2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.2
  cupertino_icons: ^1.0.2
  double_back_to_close: ^2.0.0
  dropdown_button2: ^2.0.0
  firebase_auth: ^4.2.6
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  form_field_validator: ^1.1.0
  get: 4.6.5
  local_auth: ^2.1.6
  particles_flutter: ^0.1.4

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_native_splash: ^2.2.18
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/idn-logo.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/idn-logo.png"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/idn-logo.png"
  # min_sdk_android: 21 # android min sdk min:16, default 21
  # web:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  # windows:
  #   generate: true
  #   image_path: "path/to/image.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"